services:
  - type: web
    name: django-blog
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application --bind=0.0.0.0:$PORT --workers=4"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MEDIA_ROOT
        value: /opt/render/project/src/media
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 1

databases:
  - name: django-blog-db
    databaseName: django_blog_7f9a
    user: django_blog_7f9a_user
    plan: starter
    ipAllowList: []
    settings:
      max_connections: 100
      synchronous_commit: 'on'
      work_mem: '128MB'
      maintenance_work_mem: '256MB'
      effective_cache_size: '1GB'
      shared_buffers: '512MB'
    disk:
      name: postgres_data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1