# Generated by Django 4.2.3 on 2024-11-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_increase_cloudinary_fields_length'),
        ('blog', '0002_increase_image_fields_length'),
    ]

    operations = [
    ]
