# Generated by Django 4.2.3 on 2024-11-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_profile_fields'),
        ('blog', '0003_merge_20241126_1917'),
    ]

    operations = [
    ]
