# Generated by Django 4.2.3 on 2024-12-15 17:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_merge_20241126_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='texttemplate',
            options={'ordering': ['category', 'title'], 'verbose_name': 'Шаблон текста', 'verbose_name_plural': 'Шаблоны тексов'},
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover'),
        ),
    ]
