# Generated by Django 4.2.3 on 2024-12-30 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_alter_texttemplate_options_alter_post_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='texttemplate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='pagesettings',
            name='page_name',
            field=models.CharField(choices=[('contacts', 'Страница "Связь со мной"'), ('create_post', 'Создание постов'), ('about', 'О сайте')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='texttemplate',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='texttemplate',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='texttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='texttemplate',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
