# Generated by Django 4.2.3 on 2025-01-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='additional_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='story',
            name='alt_titles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='story',
            name='chapters_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='story',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
