# Generated by Django 4.2.3 on 2025-01-03 18:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_story_additional_links_story_alt_titles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover'),
        ),
    ]
